
#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that run after cloning repository
install:
  - cmd: git submodule update --init --recursive

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: src/OpenAPI.sln    # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages

  # MSBuild verbosity level
  verbosity: normal


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

#artifacts:
#  - path: 'src\MiNET\MiNET.Service\bin\Release'


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:
  
# Deploying to a named environment
- provider: Environment
  name: NuGet
